(* File generated by gen_codes_ml.py on Mon Sep 19 20:18:47 2022. *)

open Error

let int_from_lexing_error : lexing_error -> int = function
  | Unexpected_character _ -> 101
  | Illegal_escape _ -> 102
  | Unterminated_string -> 103
  | Invalid_literal _ -> 104
  | Invalid_builtin_type _ -> 105

let int_from_syntax_error : syntax_error -> int = function
  | Expected _ -> 201
  | Unexpected -> 202
  | Unclosed _ -> 203
  | Use_of_unbound _ -> 204
  | Duplicate_parameter _ -> 205
  | Other _ -> 206

let int_from_type_error : type_error -> int = function
  | Expected _ -> 301
  | Could_not_infer -> 302

let int_from_other_error : other_error -> int = function
  | Could_not_open _ -> 401
  | Could_not_compile _ -> 402
  | Failed_to_resolve _ -> 403
  | Failed_to_import _ -> 404
  | Cannot_explain _ -> 405

let int_from_error = function
  | Lexing_error e -> int_from_lexing_error e
  | Syntax_error e -> int_from_syntax_error e
  | Type_error e -> int_from_type_error e
  | Other_error e -> int_from_other_error e

let error_name_from_int = function
  | 101 -> Some "unexpected character"
  | 102 -> Some "illegal escape sequence"
  | 103 -> Some "unterminated string"
  | 104 -> Some "invalid literal"
  | 105 -> Some "invalid builtin type"
  | 201 -> Some "expected token"
  | 202 -> Some "unexpected token"
  | 203 -> Some "unclosed token"
  | 204 -> Some "use of unbound symbol"
  | 205 -> Some "duplicate parameter"
  | 206 -> Some "other syntax error"
  | 301 -> Some "expected"
  | 302 -> Some "could not infer type"
  | 401 -> Some "could not open file"
  | 402 -> Some "could not compile file"
  | 403 -> Some "failed to resolve module"
  | 404 -> Some "failed to import module"
  | 405 -> Some "cannot explain error code"
  | _ -> None